Faulty deserializers generated when record is splitted in subsequent schema
linkedin/avro-util pull request #132
Opened 2021-02-03 17:11 UTC by flowenol

Hi,

Recently we ran into this issue while doing some refactoring on our production schemas. The aim of the refactoring was to split the already existing record into two separate records preserving the backwards compatibility via the use of type aliases.

Example: record A with aliases B and C in the next version is changed into records B and C, both of them have an alias to A.

This resulted in faulty deserializers being generated, which were unable to read the data for both reading scenarios with schemas interchanged.

The fix for this bug required some changes around method reference caching in FastDeserializerGenerator and in various places the writer schema had to altered with reader schema.

15f4495 contains the test cases with faulty deserializers code-gen
48e6b22 contains the fix with proper deserializers code-gen

cheers,
Peter

2021-02-05 23:05 UTC, gaojieliu commented
@flowenol 
Thanks for this improvement.
Could you split this code change into two commits as this one: https://github.com/linkedin/avro-util/pull/72/commits ?
One commit contains all the code gen logic and related tests, and the other one only contains the generated classes.
With this way, it will be easier for review to understand what has been changed.

Thanks

2021-02-08 10:26 UTC, wikkoz commented
Hi @gaojieliu 

I have rearranged commits as you wanted.

2021-02-08 18:31 UTC, gaojieliu commented
Hi @wikkoz 
Thank you, will review your RB soon.

2021-02-17 00:34 UTC, gaojieliu requested changes
Sorry for the late review.
The code change looks good overall, and I left a minor comment.

2021-02-17 13:34 UTC, wikkoz commented on avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSerdeTestsSupport.java
> +        nullNodeClass = Class.forName("com.fasterxml.jackson.databind.node.NullNode");
Yes here is JIRA for it
https://issues.apache.org/jira/browse/AVRO-1126

2021-02-17 13:48 UTC, wikkoz commented on avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
> +        + writerSchema.hashCode() + (readerSchema != null ? readerSchema.hashCode() : ""), method);
Done

2021-02-17 17:40 UTC, gaojieliu approved these changes

2021-02-17 17:40 UTC, merged

2021-02-17 18:01 UTC, gaojieliu commented
@wikkoz 
Please try this release: 
https://bintray.com/linkedin/maven/avro-util/0.2.25