Legacy schema writer option
linkedin/avro-util pull request #489
Opened 2023-05-10 20:12 UTC by li-ukumar

## What
Adding a legacy option in Avsc writer to generate Avsc before normalization was introduced.
Only canonicalization configs to use non-legacy option.

## Why
Some use cases Hash the serialized schemas and are now incompatible with the normalized changes. While the long-term viability of some of these usecases are questionable, in short term it means normalization will break their systems.

## Testing
Updated Unit tests

2023-05-10 20:53 UTC, dg-builder requested changes
Can we instead split this into 2 classes? `LegacyAvscWriter` and `AvscWriter`? `AvscWriter.java` is getting very long (and a lot of this code is copy-pasta

2023-05-10 23:28 UTC, li-ukumar commented
> Can we instead split this into 2 classes? `LegacyAvscWriter` and `AvscWriter`? `AvscWriter.java` is getting very long (and a lot of this code is copy-pasta

I suggest keeping AvscWriter intact and controlling what we write using configs and plugins. 
Also splitting avscwriter into parts would create quite a bit of duplicate as well

2023-05-10 23:34 UTC, dg-builder approved these changes

2023-05-11 01:35 UTC, xiaoyu-yang-gh approved these changes

2023-05-11 02:10 UTC, merged